### PR TITLE
Add support for Go 1.5 test results

### LINKED ISSUE #15: Test report will be all failure with Go1.5
Because of the test case identifying logic:

     if strings.HasPrefix(line, "=== RUN ") {
                        // new test
                        cur = line[8:]
                        tests = append(tests, &Test{
                                Name:   line[8:],
                                Result: FAIL,
                                Output: make([]string, 0),
                        })
                }

And since go 1.5 tweaked the test out put a little bit, there will be 2 more space before the actual name in the generated report, like:

    <testcase classname="A" name="  TestA" time="0.000">
		<failure message="Failed" type=""></failure>
    </testcase>

As a result, this program will not be able to update the actually status of the test cases because it could not find any matching test cases via findTest() function.

Suggest that we use regex to get the test case name, just like how we get test status.

Might submit a pull request later.

### PR DESCRIPTION
**Pull request by sectioneight**
An alternate approach that does not involve regular expressions.

Fixes #15

Similar to #16 but does not use regular expressions nor change the import path.

### CODE REVIEW

**Comment by sectioneight** [comment]
Not really sure how these tests are supposed to pass given that they all have a different version of the Go binary which outputs a different version identifier in the xml output...

**Comment by docbobo** [comment]
Here's a guess: all the other test files declare go.version like this:
```xml
<property name="go.version" value="1.0"></property>
```

The proof is in [go-junit-report_test.go](https://github.com/jstemmer/go-junit-report/blob/master/go-junit-report_test.go#L426)

**Comment by nathanjordan** [comment]
+1

**Comment by prashantv** [comment]
+1

**Comment by cduruk** [comment]
+1

**Comment by jstemmer** [comment]
Looks good, thanks for contributing!

**Pull request merged**
