### PR TITLE
Capture test output

### LINKED ISSUE #41: Data race failures aren't reported in XML output.
I think this is caused by the individual run passing, while the overall suite fails. I'm not sure what the best way to represent this in the junit.xml-- maybe make the closest testcase fail, especially if it's interleaved?

Example (from kubernetes/kubernetes#35872): 
```
=== RUN   TestNamespaceController
==================
WARNING: DATA RACE
Read at 0x00c420237758 by goroutine 20:
  reflect.Value.IsNil()
      /usr/local/go/src/reflect/value.go:975 +0xd8
  reflect.deepValueEqual()
      /usr/local/go/src/reflect/deepequal.go:70 +0xe8b
  reflect.deepValueEqual()
      /usr/local/go/src/reflect/deepequal.go:97 +0xe09
  reflect.deepValueEqual()
      /usr/local/go/src/reflect/deepequal.go:97 +0xe09
  reflect.deepValueEqual()
      /usr/local/go/src/reflect/deepequal.go:94 +0xc9b
  reflect.DeepEqual()
      /usr/local/go/src/reflect/deepequal.go:185 +0x2bb
  k8s.io/kubernetes/federation/pkg/federation-controller/util.NewTriggerOnAllChanges.func3()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/handlers.go:42 +0xc7
  k8s.io/kubernetes/pkg/client/cache.ResourceEventHandlerFuncs.OnUpdate()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:175 +0x6f
  k8s.io/kubernetes/pkg/client/cache.(*ResourceEventHandlerFuncs).OnUpdate()
      <autogenerated>:51 +0xb0
  k8s.io/kubernetes/pkg/client/cache.NewInformer.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:241 +0x3ab
  k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:420 +0x36b
  k8s.io/kubernetes/pkg/client/cache.(*Controller).processLoop()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:126 +0x70
  k8s.io/kubernetes/pkg/client/cache.(*Controller).(k8s.io/kubernetes/pkg/client/cache.processLoop)-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:102 +0x41
  k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87 +0x6f
  k8s.io/kubernetes/pkg/util/wait.JitterUntil()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:88 +0xbd
  k8s.io/kubernetes/pkg/util/wait.Until()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49 +0x5a
  k8s.io/kubernetes/pkg/client/cache.(*Controller).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/controller.go:102 +0x24e

Previous write at 0x00c420237758 by goroutine 23:
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).addFinalizerFunc()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:228 +0x159
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).(k8s.io/kubernetes/federation/pkg/federation-controller/namespace.addFinalizerFunc)-fm()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:174 +0x76
  k8s.io/kubernetes/federation/pkg/federation-controller/util/deletionhelper.(*DeletionHelper).EnsureFinalizers()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/deletionhelper/deletion_helper.go:101 +0x39f
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).reconcileNamespace()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:359 +0x29a
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).Run.func2()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:272 +0xb8
  k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:176 +0x105

Goroutine 20 (running) created at:
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:264 +0x73
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.TestNamespaceController()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:113 +0x151a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Goroutine 23 (running) created at:
  k8s.io/kubernetes/federation/pkg/federation-controller/util.(*DelayingDeliverer).StartWithHandler()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/util/delaying_deliverer.go:181 +0x56
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.(*NamespaceController).Run()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller.go:273 +0x155
  k8s.io/kubernetes/federation/pkg/federation-controller/namespace.TestNamespaceController()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/namespace/namespace_controller_test.go:113 +0x151a
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
==================
--- PASS: TestNamespaceController (1.16s)
PASS
Found 1 data race(s)
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/namespace	3.373s
=== RUN   TestParseFederationReplicaSetReference
--- PASS: TestParseFederationReplicaSetReference (0.00s)
```

output:
```
<testsuite tests="1" failures="0" time="3.373" name="k8s.io/kubernetes/federation/pkg/federation-controller/namespace">
<properties>
<property name="go.version" value="go1.7.1"/>
</properties>
<testcase classname="namespace" name="TestNamespaceController" time="1.160"/>
</testsuite>
```

### PR DESCRIPTION
**Pull request by IngmarStein**
This PR
* captures more of the test output which seems to have been swallowed previously.
* improves the regular expressions for coverage results to match percentages without decimal point, e.g. ("10% of statements").
* adds Go 1.8 to the Travis build matrix.

This should fix #41

### CODE REVIEW

**Comment by IngmarStein** [comment]
Ping @jstemmer

**Comment by jstemmer** [comment]
Thanks for the PR. I'm currently traveling, but I'll take a look when I get
back in ~2 weeks.

**Comment by IngmarStein** [comment]
Back?

**Comment by IngmarStein** [comment]
There's other trailing output as seen in #41. For example: `Found 1 data race(s)`. If you think that's not potentially valuable, I'll remove that from this PR. To my eyes, output that may be attributed to the wrong test is still better than hiding messages that may be interesting.

Regarding the coverage report without decimals, I had looked at the test `10-multipkg-coverage.txt` and mistakenly parsed the test output `coverage: 10% of statements` instead of the summary line that follows immediately (which always includes decimals). Fixed.

**Comment by jstemmer** [comment]
So far I haven't encountered anything that would be valuable to capture. The exit status isn't that important when you have the test results, the number of data races could potentially be interesting but the stacktrace is printed and you have a failing test to fix, and the coverage output looks like noise to me. 

I may have missed something, but if there is value in capturing this output we may also consider creating a dummy test with that output as was done in other situations. I'd prefer to discuss that separately once there's a convincing example however.

**Comment by IngmarStein** [comment]
Removed captured output as requested.

**Comment by jstemmer** [comment]
Looks good, thanks!

**Pull request merged**
