### PR TITLE
Allow output to be written to file and input to go to stdout.

### PR DESCRIPTION
**Pull request by BlueDragonX**
I'd like to have the option to print the `go test` output as well as generate the report. This does that.

This functionality is important because the regular `go test` output includes more details.

### CODE REVIEW

**Comment by willdurand** [comment]
:+1:

**Comment by rmmh** [comment]
The normal usage is:

    go test -v | go-junit-report > report.xml

Why not use tee for this?

    go test -v | tee report.txt | go-junit-report > report.xml

Or

    go test -v | tee -a report.txt | go-junit-report > report.xml

**Comment by BlueDragonX** [comment]
Your usage of tee outputs to a file. My update outputs to stdout.

Doesn't matter much. I'm now tee'ing to an intermediate file and cat'ing that to this tool.

**Comment by rmmh** [comment]
Oh, that makes sense. You can use bash process substitution for this:

    go test -v | tee >(go-junit-report > report.xml)

We can add that to the README.

**Comment by jhg03a** [comment]
A full example without pipefail might look like:
```
(go test -v 2>&1 | tee tests.log && exit ${PIPESTATUS[0]}) | ./go-junit-report --package-name=golang.test.unit --set-exit-code > tests.junit.xml
```

**Comment by janisz** [comment]
How to use this on Windows builds?
I think flag to print input to stdout will help with cross platform scripts. Eg `/dev/stderr` does not exist on Windows.

**Comment by jstemmer** [comment]
Thanks for the PR. The recently released v2.0.0 supports writing output to a file and writing the input to stdout. I no longer intend to maintain the old v1 branch, so I'm closing this PR.

**Pull request closed without merging**
