### PR TITLE
Include test output and stdout in test failures

### PR DESCRIPTION
**Pull request by liggitt**
Scraped test output from tests run with go1.11.1 was ending at the `--- FAIL` line, and was not including the actual error/info output

The existing code that assumes tab-prefixed indented output does not work with go1.11.1. This PR accumulates appropriately indented lines into the current test's output.

Adds a test with mixtures of single- and multi-line stdout and test output, with normal and subtests, based on running `go test -v` on https://gist.github.com/liggitt/09a021ccec988b19917e0c2d60a18ee9 with go1.11.1

### CODE REVIEW

**Comment by liggitt** [comment]
xref https://github.com/kubernetes/test-infra/issues/10539

**Comment by dims** [comment]
@jstemmer post holiday ping :) we need this for better capturing logs for some tricky bugs like this [one](https://github.com/kubernetes/kubernetes/issues/71696)

**Comment by jstemmer** [comment]
@dims thanks for the ping! Will take a look at all PR's within the next couple of days.

**Comment by jhg03a** [comment]
Tested this with my fork and it seems to fix my issues.

**Comment by dims** [comment]
Thanks for the confirmation @jhg03a

**Comment by jstemmer** [comment]
Looks great, thanks for fixing this!

**Pull request merged**
