### PR TITLE
Add support for sub-tests in 1.7

### LINKED ISSUE #38: Subtests (go 1.7) interpreted as failures
The following output from `go test -v | go-junit-report` results in false positives for errors.

Test results

```
=== RUN   TestFUpload
=== RUN   TestFUpload/POSTs_with_filename_body_result_in_200
--- PASS: TestFUpload (0.00s)
    --- PASS: TestFUpload/POSTs_with_filename_body_result_in_200 (0.00s)
=== RUN   TestFDownload
=== RUN   TestFDownload/GETs_return_signed_url
--- PASS: TestFDownload (0.00s)
    --- PASS: TestFDownload/GETs_return_signed_url (0.00s)
=== RUN   TestFDownloadHandlesEdges
--- PASS: TestFDownloadHandlesEdges (0.00s)
=== RUN   TestHealthEndpoint
--- PASS: TestHealthEndpoint (0.00s)
PASS
ok      github.com/ployst/ployst/pfs/fileservice        0.027s
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
        <testsuite tests="6" failures="2" time="0.023" name="github.com/ployst/ployst/pfs/fileservice">
            <properties>
                <property name="go.version" value="go1.5.1"></property>
            </properties>
            <testcase classname="fileservice" name="TestFUpload" time="0.000"></testcase>
            <testcase classname="fileservice" name="TestFUpload/POSTs_with_filename_body_result_in_200" time="0.000">
                <failure message="Failed" type=""></failure>
            </testcase>
            <testcase classname="fileservice" name="TestFDownload" time="0.000"></testcase>
            <testcase classname="fileservice" name="TestFDownload/GETs_return_signed_url" time="0.000">
                <failure message="Failed" type=""></failure>
            </testcase>
            <testcase classname="fileservice" name="TestFDownloadHandlesEdges" time="0.000"></testcase>
            <testcase classname="fileservice" name="TestHealthEndpoint" time="0.000"></testcase>
        </testsuite>
</testsuites>
```

Also not sure why golang is being detected by this library as 1.5.1
$ go version
go version go1.7.1 darwin/amd64

### PR DESCRIPTION
**Pull request by sectioneight**
Fixes #38

This builds off of #36 and fixes support for output messages from tests, as well as updating Travis targets.

### CODE REVIEW

**Comment by sectioneight** [comment]
@jstemmer thoughts?

**Comment by nubunto** [comment]
Any idea on when this is going to be available upstream?

**Comment by garukun** [comment]
Ping @jstemmer. We'd like to vendor this change off of master if possible :)

**Comment by sectioneight** [comment]
We've ended up switching to https://github.com/sectioneight/go-junit-report at Uber -- I plan on maintaining compatibility with recent versions of Go since Uber aggressively upgrades to new compilers if you'd like to switch. I'll gladly accept PRs there :)

**Comment by rmmh** [comment]
@sectioneight Kubernetes uses this too. I've gotten jstemmer to add me as a collaborator, so we can use this common repo to work off of-- I'm going to make it recognize data race detector errors properly.

**Comment by sectioneight** [comment]
Awesome news. I'll switch Uber back to this repo.

**Comment by sectioneight** [comment]
@jstemmer any interest in adding me as a contributor as well? I've contributed a few patches now and am the lead Go evangelist (and bug fixer of things like this) and would love to contribute in a more expedient manner if possible, rather than pushing us onto long-lived forks.

**Comment by jstemmer** [comment]
@sectioneight sure! Some help is more than welcome, and thanks for your contributions.

**Comment by sectioneight** [comment]
Hooray@ Thanks @jstemmer. Much apreciated.

**Pull request merged**
